server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: http://192.168.254.100:9200
  rabbitmq:
    host: 192.168.254.100
    username: lee552
    password: lee552
    virtual-host: /lee552