server:
  port: 8081
spring:
  application:
    name: pms-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://192.168.254.100:3306/guli_pms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增